baseURL = "https://quantum.ahughes.dev"
languageCode = "en-gb"
title = "Quantum Notes"
theme = "ezhil"


copyright = "Copyright © 2021 Andrew Hughes"
author = "Andrew Hughes"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  mode = "light"

[markup.goldmark.renderer]
  unsafe = true
